spring:
  datasource:
    url: jdbc:mysql://192.168.0.159:3306/2cloud?serverTimezone=GMT%2B8
    username: 2cloud
    password: zZtaay8SLxsNjKJF
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
server:
  port: 8081
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
